version: '3.8'

services:
  web:
    build: .
    container_name: php-web
    ports:
      - "8080:80"
    volumes:
      - /Applications/XAMPP/xamppfiles/htdocs/UniMeStudentSys:/var/www/html
    depends_on:
      - mysql
      - mongo
      - neo4j

  mysql:
    image: mysql:latest
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: UniMe
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    

  mongo:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    command: >
      bash -c "
        apt-get update && \
        apt-get install -y gnupg wget && \
        wget -qO - https://www.mongodb.org/static/pgp/server-5.0.asc | gpg --dearmor > /usr/share/keyrings/mongodb-archive-keyring.gpg && \
        echo 'deb [signed-by=/usr/share/keyrings/mongodb-archive-keyring.gpg] https://repo.mongodb.org/apt/debian buster/mongodb-org/5.0 main' | tee /etc/apt/sources.list.d/mongodb-org-5.0.list && \
        apt-get update && \
        apt-get install -y mongodb-org-tools && \
        tail -f /dev/null
      "

  neo4j:
    image: neo4j:latest
    container_name: neo4j-db
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password
    volumes:
      - neo4j_data:/data

volumes:
  mysql_data:
  mongo_data:
  neo4j_data:
